
name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        # FIXME: Python matrix
      - name: Install required Python dependencies
        run: >
          pip install nox
          pip install flit
      - name: Run nox
        # Run tox using the version of Python in `PATH`
        run: nox
      - name: Package artifacts
        run: flit build
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
      - name: Publish package to TestPyPI # Always publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
