
name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        # FIXME: Python matrix
      - name: Install required Python dependencies
        run: >
          pip install nox
          pip install flit
      - name: Run nox
        # Run tox using the version of Python in `PATH`
        run: nox
