
name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        # FIXME: Python matrix
      - name: Install required Python dependencies
        run: >
          pip install nox
          pip install flit
      - name: Run nox
        # Run tox using the version of Python in `PATH`
        run: nox
      - name: Package artifacts
        run: flit build
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
  publish:
    name: Publish package
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

